services:
  - type: web
    name: black-webplayer
    runtime: node
    rootDir: webplayer
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
